//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicNumber3 {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceText() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagicNumber3.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   【エラー】 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【詳細】 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INFO {
            get {
                return ResourceManager.GetString("INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しくない数字が入力されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string logErrorIncorrectNum {
            get {
                return ResourceManager.GetString("logErrorIncorrectNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロセスが正常に完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string logInfoNormalEnd {
            get {
                return ResourceManager.GetString("logInfoNormalEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VOICEVOX_SoundData\\どんな数字も最後には３になってしまいます。...怪しいポイントでトリックを見破ってみましょう！.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string soundPath0 {
            get {
                return ResourceManager.GetString("soundPath0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VOICEVOX_SoundData\\20240504_その数字に5を掛け…_003.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string soundPath1 {
            get {
                return ResourceManager.GetString("soundPath1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VOICEVOX_SoundData\20240506_最初の数字で割ると…_001.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string soundPath10 {
            get {
                return ResourceManager.GetString("soundPath10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VOICEVOX_SoundData\20240506_お疲れ様でした！_002.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string soundPath11 {
            get {
                return ResourceManager.GetString("soundPath11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VOICEVOX_SoundData\\20240505_その数字に2を掛け…_002.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string soundPath2 {
            get {
                return ResourceManager.GetString("soundPath2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VOICEVOX_SoundData\\20240505_最初の数字で割って…_003.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string soundPath3 {
            get {
                return ResourceManager.GetString("soundPath3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VOICEVOX_SoundData\20240505_７を引いてください。_001.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string soundPath4 {
            get {
                return ResourceManager.GetString("soundPath4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VOICEVOX_SoundData\20240505_３になりましたね？ _002.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string soundPath5 {
            get {
                return ResourceManager.GetString("soundPath5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VOICEVOX_SoundData\20240505_ここではありません…_003.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string soundPath6 {
            get {
                return ResourceManager.GetString("soundPath6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VOICEVOX_SoundData\20240506_どれが答えでしょう_001.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string soundPath7 {
            get {
                return ResourceManager.GetString("soundPath7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VOICEVOX_SoundData\20240506_違いますよ！_002.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string soundPath8 {
            get {
                return ResourceManager.GetString("soundPath8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VOICEVOX_SoundData\20240506_正解です！_003.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string soundPath9 {
            get {
                return ResourceManager.GetString("soundPath9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その数字に5を掛けた数字を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stringBtnDecisionClicked1 {
            get {
                return ResourceManager.GetString("stringBtnDecisionClicked1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その数字に2を掛けた数字を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stringBtnDecisionClicked2 {
            get {
                return ResourceManager.GetString("stringBtnDecisionClicked2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最初の数字で割ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stringBtnDecisionClicked3 {
            get {
                return ResourceManager.GetString("stringBtnDecisionClicked3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ７を引いてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stringBtnDecisionClicked4 {
            get {
                return ResourceManager.GetString("stringBtnDecisionClicked4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ３になりましたね？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stringBtnDecisionClicked5 {
            get {
                return ResourceManager.GetString("stringBtnDecisionClicked5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トリックの正体は？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stringBtnPointOutClicked1 {
            get {
                return ResourceManager.GetString("stringBtnPointOutClicked1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ここではありません！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stringBtnPointOutClicked2 {
            get {
                return ResourceManager.GetString("stringBtnPointOutClicked2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しい数値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stringMissNumber1 {
            get {
                return ResourceManager.GetString("stringMissNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ここではありません！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stringMissNumber2 {
            get {
                return ResourceManager.GetString("stringMissNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   どんな数字も最後には３になってしまいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stringOp1 {
            get {
                return ResourceManager.GetString("stringOp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   怪しいポイントでトリックを見破ってみましょう！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stringOp2 {
            get {
                return ResourceManager.GetString("stringOp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   違いますよ！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stringPointOut1 {
            get {
                return ResourceManager.GetString("stringPointOut1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正解です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stringPointOut2 {
            get {
                return ResourceManager.GetString("stringPointOut2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最初の数字で割るとどんな数字でも必ず10になりますね！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stringPointOut3 {
            get {
                return ResourceManager.GetString("stringPointOut3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お疲れ様でした！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stringPointOut4 {
            get {
                return ResourceManager.GetString("stringPointOut4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stringSwitchEvent {
            get {
                return ResourceManager.GetString("stringSwitchEvent", resourceCulture);
            }
        }
    }
}
